### ISSUE TITLE
Add WP 5.0 to the list 😎

### ISSUE THREAD

**Issue by jrfoell** [salcode/wordpress-to-gutenberg-version#1]

**Comment by salcode** [comment]
On the [wordpress/gutenberg](https://github.com/wordpress/gutenberg) repo, they have the following branches:

- [wp/5.3](https://github.com/WordPress/gutenberg/tree/wp/5.3)
- [wp/5.2](https://github.com/WordPress/gutenberg/tree/wp/5.2)
- [wp/5.1](https://github.com/WordPress/gutenberg/tree/wp/5.1)

however they do not have a branch `wp/5.0`

I have no objections to adding WordPress version `5.0` to the list, I just don't know what commit in the Gutenberg repository corresponds to to it. If anyone wants to update this issue with the correct commit (and an explanation of how they know it is the correct commit), I'm happy to add this.

**Comment by salcode** [comment]
Closed in favor of #4
